apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: informasjonsmodell-documentation
  name: informasjonsmodell-documentation
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: informasjonsmodell-documentation
  template:
    metadata:
      labels:
        io.kompose.service: informasjonsmodell-documentation
    spec:
      containers:
        - name: informasjonsmodell-documentation
          image: fintlabs.azurecr.io/information-model-documentation-portal:build.5
          ports:
            - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 3000
              path: /health
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: GITHUB_ORGANISATION
              value: FINTLabs
        - name: informasjonsmodell-documentation-metamodell
          image: fintlabs.azurecr.io/information-model-documentation-portal:meta.2
          ports:
            - containerPort: 3001
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            httpGet:
              port: 3001
              path: /health
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: GITHUB_ORGANISATION
              value: FINTLabs
            - name: GITHUB_REPO
              value: FINT-informasjonsmodell-metamodell
            - name: EA_XMI_FILENAME
              value: FINT-metamodell.xml
            - name: PORT
              value: "3001"